Vagrant.configure("2") do |config|
  config.vm.define "webserver" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.network "public_network"
    web.vm.synced_folder "./shared_web", "/home/vagrant/shared_web", create: true
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y nginx
    SHELL
  end
  config.vm.define "private" do |pr|
    pr.vm.box = "ubuntu/xenial64"
    pr.vm.network "private_network", ip: "192.168.50.10"
    pr.vm.synced_folder "./shared_web", "/home/vagrant/shared_web", create: true
    pr.vm.provision "shell", path: "./install.sh"
  end
  config.vm.define "attached" do |at|
    at.vm.box = "ubuntu/xenial64"
    at.vm.network "public_network", bridge: "Wireless LAN adapter Беспроводная сеть"
    at.vm.synced_folder "./shared_private", "/home/vagrant/shared_private", create: true
    at.vm.provision "shell", path: "./install.sh"
  end
end   
